### ISSUE TITLE
store creation access

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/flask-online-store#1]
Currently anyone who logs in can create a store , we want to have two classes of people customers and sellers.

We can achieve that by adding a parameter to all users which determines whether they are customers or sellers , if parameter is not passed during user creation they must be customer .

Only sellers must have permission to create stores and delete them , so database schema and request parameters must be handled appropriately .

**Comment by rpdswtk** [comment]
Hi!
I would like to work on this issue.

**Comment by DiptoChakrabarty** [comment]
Sure @rpdswtk please go ahead

**Comment by DiptoChakrabarty** [comment]
Issue solved working
