### ISSUE TITLE
Docker deployment of the app

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/flask-online-store#2]
Currently we are able to run the application locally using python.

It would be great if we could have docker images and a docker compose file to launch the application .

Images for flask app and database would be required.

**Comment by benji011** [comment]
Hi @DiptoChakrabarty if you assign this to me I can give this a shot

**Comment by DiptoChakrabarty** [comment]
Sure @benji011 please go ahead

**Comment by benji011** [comment]
Thanks. By the way you need to add the `hacktoberfest` topic to this repo [as per updated guidelines here](https://hacktoberfest.digitalocean.com/hacktoberfest-update). Just a friendly FYI :)

**Comment by DiptoChakrabarty** [comment]
Thanks I have added it now
