### ISSUE TITLE
password of user

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/flask-online-store#3]
Due to use github oauth as we do not consider any password , the password parameter in database has been kept as nullable= False , this must be changed to True.

For users  using github login random sample passwords must be generated to store in database.

Please check the code to understand further.

**Comment by gabrielhicks** [comment]
Hi I would like to try to work on this issue.

**Comment by DiptoChakrabarty** [comment]
go ahead @gabrielhicks

**Comment by yashrsb** [comment]
@DiptoChakrabarty I would like to work on this issue . Please assign this to me.

**Comment by gabrielhicks** [comment]
@TechnoPhasePRO I opened a PR #11 if you want to check it out and see if its a solution

**Comment by DiptoChakrabarty** [comment]
> @DiptoChakrabarty I would like to work on this issue . Please assign this to me.

Hey @TechnoPhasePRO  this issue has been solved already and its working you can try some of the other issues present
