### ISSUE TITLE
order input modification

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/flask-online-store#5]
Currently to order a single item multiple times we have to enter the item name that many times , this should be changed to just order item and no of items as inputs 

Something similar to  mango,5  which confirms ordering 5 mangos

**Comment by pulkitsapra** [comment]
I want to work on this. Please assign it to me.

**Comment by DiptoChakrabarty** [comment]
sure go ahead @pulkitsapra

**Comment by pulkitsapra** [comment]
@DiptoChakrabarty Currently, the input for parameter is a json with key "items" . But in value you are taking string only. So in case the item name is more than 1 character, it fails .

Kindly see these 3 Screenshots.

<img width="857" alt="Screenshot 2020-10-04 at 7 05 58 PM" src="https://user-images.githubusercontent.com/16730739/95012587-d259b700-0674-11eb-830c-5dd91577ca62.png">
<img width="870" alt="Screenshot 2020-10-04 at 7 06 30 PM" src="https://user-images.githubusercontent.com/16730739/95012591-dab1f200-0674-11eb-956a-52f1cf5ee6e7.png">
<img width="868" alt="Screenshot 2020-10-04 at 7 06 45 PM" src="https://user-images.githubusercontent.com/16730739/95012594-e1406980-0674-11eb-805f-df3a97edc94c.png">

**Comment by DiptoChakrabarty** [comment]
Issue solved , working
